name: S3Upload
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ASIAYERNKFVRXS453NML
          AWS_SECRET_ACCESS_KEY: 0ldCVRb33hn+IyT9VWZjbMpagmJQh8UkNU2bLVMX
        run: |
          aws s3 cp Database Technologies/NoSQL.txt s3://project2022dbdagroup3/Test/
